### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [pnakis/qgis_vector_transform#1]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by pnakis** [comment]
Hello pcav,
Thanks for bringing the issue to my attention, i deleted all .pyc files.
Should i also delete help, i18n, scripts and test folders?
Do i need to re-upload the plugin in the repository after i make all the changes?

**Comment by pcav** [comment]
i18n etc. are useful, please do not delete it.
if your zip contains .pyc, please upload a new version without.
Please note that you can simplify the directory structure, moving content of VectorTranformation up one dir.
Thanks.

**Comment by pnakis** [comment]
Plugin cleaned and re-uploaded. 
Thank you for your assistance.
